# Generated by Django 4.1.2 on 2023-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=200),
        ),
    ]
