# Generated by Django 4.1.2 on 2023-02-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_description_alter_blog_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog", old_name="release_date", new_name="date",
        ),
    ]
