# Generated by Django 4.1.2 on 2023-02-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blog"),
    ]

    operations = [
        migrations.DeleteModel(name="Blog",),
    ]
